/* 

BEFORE RUNNING THE USER MUST CHANGE TWO PATHS COMMENTED IN THE CODE BELOW

this script is utilized as part of the calibElectrons github repositiory to calculate the azimuth and zenith angles of the Bi source electron trajectories. This script is ran by angles.sh, which creates a
local folder for each source and creates and runs a copy of this script. 

This script assumes that the inputted data has ran through the SNCuts pipeline for calibration electrons (i.e., it was generated by the BiCali_template_indiv_sources framework in the repositiory).
Hence, the script assumes that the events present in the PTD bank are only of a single electron that came from the calibration source.
 
The script takes the inputted data, sorts it into electrons that did and did not interact with the copper envelope and then calculates the angle of the trajectory according to the angle conventions given in the repository.
In order to process massive amounts of ROOT files from the data generation framework, this script chains together the ROOT files that reside in the data framework's ROOTFiles subdirectory. No additional input is needed from 
the user to merge together multiple ROOT files in this directory.

The terminology for interacting with the envelope is as follows:

envelope interaction: the particle's SD bank has atleast one calorimeter hit associated with the envelope (atleast one hit has GID=1066). 
no envelope interaction: the particle's SD bank has no calorimeter hits associated with the envelope (no hit has GID=1066).

The script outputs two root files: one that contains the angles of the envelope-interacting electrons and another that contains the angles of the electrons that don't interact with the envelope. 
A text file that contains a count of events in each ROOT file is also generated.

*/

//user must change this path to where their MiModule is located.
#include "/sps/nemo/scratch/apitolaj/Modules/MiModule/include/MiEvent.h"
#include "UTILS_PLACEHOLDER/functionUtils.h"
#include "TLatex.h"
#include "TVector3.h"
#include <string>
#include <iostream>
#include <sstream>
#include <algorithm>
#include "TSystemDirectory.h"
#include "TSystemFile.h"
#include "TList.h"

//user must change this path to where their MiModule is located.
R__LOAD_LIBRARY(/sps/nemo/scratch/apitolaj/Modules/MiModule/lib/libMiModule.so);

void angles_600_800keV_chainROOT_Source_SOURCE_PLACEHOLDER()
{
	float azimuth;
	float zenith;
	int eventNumber;
	
	TChain chain("Event");
	populateChain(chain, "BASE_PLACEHOLDER/../SOURCES/Source_SOURCE_PLACEHOLDER/DATA/ROOTFiles");

	MiEvent *Eve = new MiEvent();
	chain.SetBranchAddress("Eventdata", &Eve);
	
	TFile *outFile_envelope = new TFile("BASE_PLACEHOLDER/DST_PLACEHOLDER/angles_envelope_600_800keV_Source_SOURCE_PLACEHOLDER.root", "RECREATE");
	TTree *tr_envelope = new TTree("azimuth_zenith", "contains the azimuth and zenith angles of fitted 3D direction of electrons that DID pass through the envelope");

	tr_envelope->Branch("azimuth", &azimuth);
	tr_envelope->Branch("zenith", &zenith);
	tr_envelope->Branch("eventNum", &eventNumber);
	
	TFile *outFile_noEnvelope = new TFile("BASE_PLACEHOLDER/DST_PLACEHOLDER/angles_noEnvelope_600_800keV_Source_SOURCE_PLACEHOLDER.root", "RECREATE");
	TTree *tr_noEnvelope = new TTree("azimuth_zenith", "contains the azimuth and zenith angles of fitted 3D direction of electrons that DID NOT pass through the envelope");

	tr_noEnvelope->Branch("azimuth", &azimuth);
	tr_noEnvelope->Branch("zenith", &zenith);
	tr_noEnvelope->Branch("eventNum", &eventNumber);
	
	int energyCount =0;

	for (int i = 0; i < chain.GetEntries(); i++)
	{
		chain.GetEntry(i);
		
		
		if(isEnergyBetween600_800keV(Eve))
		{	
		
			energyCount++;
			
			if (isCalibElectron_envelope(Eve))
			{
			    eventNumber = i;
			    zenith = calculateZenith(Eve);
			    azimuth = calculateAzimuth(Eve);
			    tr_envelope->Fill();
			}
			else if (isCalibElectron_noEnvelope(Eve))
			{
			    eventNumber = i;
			    zenith = calculateZenith(Eve);
			    azimuth = calculateAzimuth(Eve);
			    tr_noEnvelope->Fill();
			}
		}
	}
	
	outFile_envelope->cd();
	tr_envelope->Write();

	outFile_noEnvelope->cd();
	tr_noEnvelope->Write();

    	std::ofstream outFile("BASE_PLACEHOLDER/DST_PLACEHOLDER/angles_entryCounts_600_800keV_Source_SOURCE_PLACEHOLDER.txt");
    	
    	outFile << "Entry count (of electrons only in the 600-800 keV range)" << std::endl;
	outFile << "Envelope: " << tr_envelope->GetEntries() << std::endl;
	outFile << "No Envelope: " << tr_noEnvelope->GetEntries() << std::endl;
	outFile << "Total: " << energyCount << std::endl;
	
	outFile.close();
	outFile_envelope->Close();
	outFile_noEnvelope->Close();
}
